### ISSUE TITLE
Configuration for tomcat6x

### ISSUE THREAD

**Issue by Alcastic** [bmuschko/gradle-cargo-plugin#140]
This is my build.gradle

    buildscript {
        ext {
            springBootVersion = '1.2.6.RELEASE'
        }
        repositories {
            mavenCentral()
            jcenter()
        }
        dependencies {
            classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}") 
            classpath('io.spring.gradle:dependency-management-plugin:0.5.2.RELEASE')
            classpath 'com.bmuschko:gradle-cargo-plugin:2.2.1'
        }
    }

    apply plugin: 'java'
    apply plugin: 'war'
    apply plugin: 'eclipse-wtp'
    apply plugin: 'idea'
    apply plugin: 'spring-boot'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'jetty'
    apply plugin: 'sonar-runner'
    apply plugin: 'com.bmuschko.cargo'

    war {
        baseName = 'SampleSpringREST'
        version = '0.0.1-SNAPSHOT'
    }
    
    sourceCompatibility = 1.7
    targetCompatibility = 1.7

    repositories {
        mavenCentral()
    }

    configurations {
        providedRuntime
    }

    dependencies {
    	// Spring
        compile('org.springframework.boot:spring-boot-starter-web')
        providedRuntime('org.springframework.boot:spring-boot-starter-tomcat')
        testCompile('org.springframework.boot:spring-boot-starter-test')

        // Lombok
        compile('org.projectlombok:lombok:1.16.6')

        // Hibernate
        compile 'org.hibernate:hibernate-entitymanager:4.3.10.Final'
    
        // Postgres Driver
        compile 'org.postgresql:postgresql:9.3-1102-jdbc41'
    
        // Mongodb Driver
    	compile 'org.mongodb:mongo-java-driver:3.0.0'

        // JSON
        testCompile ('com.jayway.jsonpath:json-path:0.8.1')
        compile 'com.google.code.gson:gson:2.3.1'
        compile 'org.codehaus.jackson:jackson-mapper-asl:1.9.13'

    	// Log4j
        compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.1'

        // Mockito
        testCompile('org.mockito:mockito-all:1.9.5')
    
    	// JUnit
        testCompile group: 'junit', name: 'junit', version: '4.+'

        // cucumber tests
        testCompile("info.cukes:cucumber-junit:1.1.8")
        testCompile("info.cukes:cucumber-java:1.1.8")
    
        // Others
        compile 'jstl:jstl:1.2'
        compile 'cglib:cglib-nodep:3.1'
    
        //Gradle-Cargo-Plugin
        def cargoVersion = '1.4.5'
        cargo "org.codehaus.cargo:cargo-core-uberjar:$cargoVersion",
              "org.codehaus.cargo:cargo-ant:$cargoVersion"
 
    }

    cargo {
        containerId = 'tomcat6x'
        port = 9090
        remote {
            hostname = 'localhost'
        }
  
        deployable {
            context = 'SampleSpringREST'
        }
        
        local {
            homeDir = file('/home/alcastic/dev/tools/apache-tomcat-6.0.32')
            outputFile = file('build/output.log')
            timeout = 60000
    
            containerProperties {
                property 'cargo.tomcat.ajp.port', 9099
            }
        }
    
    }

    eclipse {
        classpath {
             containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
             containers         'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMTyp    e/JavaSE-1.7'
        }
    }

    task wrapper(type: Wrapper) {
        gradleVersion = '2.7'
    }

When I execute the task: cargoRunLocal
I get:

    :cargoRunLocal
    org.codehaus.cargo.container.ContainerException: Failed to create a Tomcat 6.x standalone configuration
    :cargoRunLocal FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':cargoRunLocal'.
    > org.codehaus.cargo.container.ContainerException: Failed to create a Tomcat 6.x standalone configuration

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 7.679 secs

Note: My directory "/home/alcastic/dev/tools/apache-tomcat-6.0.32" is empty, I need put something there?

**Comment by bmuschko** [comment]
Run the task with `-s` to show the stack trace. That should give you more information.

**Comment by Alcastic** [comment]
:cargoRunLocal
org.codehaus.cargo.container.ContainerException: Failed to create a Tomcat 6.x standalone configuration
:cargoRunLocal FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cargoRunLocal'.
> org.codehaus.cargo.container.ContainerException: Failed to create a Tomcat 6.x standalone configuration

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cargoRunLocal'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:158)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:36)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:103)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:102)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: : org.codehaus.cargo.container.ContainerException: Failed to create a Tomcat 6.x standalone configuration
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
	at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:77)
	at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:92)
	at com.bmuschko.gradle.cargo.tasks.local.LocalCargoContainerTask.runAction(LocalCargoContainerTask.groovy:170)
	at com.bmuschko.gradle.cargo.tasks.AbstractCargoContainerTask$_start_closure2.doCall(AbstractCargoContainerTask.groovy:92)
	at com.bmuschko.gradle.cargo.tasks.AbstractCargoContainerTask$_start_closure2.doCall(AbstractCargoContainerTask.groovy)
	at com.bmuschko.gradle.cargo.util.LoggingHandler.withAntLoggingListener(LoggingHandler.groovy:36)
	at com.bmuschko.gradle.cargo.util.LoggingHandler$withAntLoggingListener.call(Unknown Source)
	at com.bmuschko.gradle.cargo.tasks.AbstractCargoContainerTask.start(AbstractCargoContainerTask.groovy:91)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 57 more
Caused by: org.codehaus.cargo.container.ContainerException: Failed to create a Tomcat 6.x standalone configuration
	at org.codehaus.cargo.container.spi.configuration.AbstractLocalConfiguration.configure(AbstractLocalConfiguration.java:267)
	at org.codehaus.cargo.container.spi.configuration.builder.AbstractStandaloneLocalConfigurationWithXMLConfigurationBuilder.configure(AbstractStandaloneLocalConfigurationWithXMLConfigurationBuilder.java:123)
	at org.codehaus.cargo.container.spi.AbstractLocalContainer.start(AbstractLocalContainer.java:199)
	at org.codehaus.cargo.ant.CargoTask.executeActions(CargoTask.java:566)
	at org.codehaus.cargo.ant.CargoTask.execute(CargoTask.java:513)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	... 73 more
Caused by: org.codehaus.cargo.util.CargoException: Failed to copy source directory [/home/alcastic/dev/tools/apache-tomcat-6.0.32/conf] to [/tmp/cargo/conf/conf]
	at org.codehaus.cargo.util.DefaultFileHandler.copyDirectory(DefaultFileHandler.java:247)
	at org.codehaus.cargo.util.DefaultFileHandler.copyDirectory(DefaultFileHandler.java:215)
	at org.codehaus.cargo.container.tomcat.internal.AbstractCatalinaStandaloneLocalConfiguration.doConfigure(AbstractCatalinaStandaloneLocalConfiguration.java:123)
	at org.codehaus.cargo.container.spi.configuration.AbstractLocalConfiguration.configure(AbstractLocalConfiguration.java:263)
	... 79 more
Caused by: /home/alcastic/dev/tools/apache-tomcat-6.0.32/conf does not exist.
	at org.apache.tools.ant.types.AbstractFileSet.getDirectoryScanner(AbstractFileSet.java:484)
	at org.apache.tools.ant.taskdefs.Copy.execute(Copy.java:487)
	at org.codehaus.cargo.util.DefaultFileHandler.copyDirectory(DefaultFileHandler.java:243)
	... 82 more


BUILD FAILED

Total time: 6.983 secs

**Comment by bmuschko** [comment]
`Caused by: /home/alcastic/dev/tools/apache-tomcat-6.0.32/conf does not exist.`

Looks like you do not have a valid Tomcat installation.

**Comment by Alcastic** [comment]
it's possible to work without container installation in my computer?

**Comment by bmuschko** [comment]
Yes, see ["Automatically bootstrapping a local container"](https://github.com/bmuschko/gradle-cargo-plugin#automatically-bootstrapping-a-local-container) in README.

**Comment by Alcastic** [comment]
ok, thanks you for all! nice plugin.
