### ISSUE TITLE
Wrong folder configuration?

### ISSUE THREAD

**Issue by tomasbabic** [bmuschko/gradle-cargo-plugin#38]
Hi,

I am having trouble to deploy my war locally. Here is a snippet of my build.gradle
    buildscript {
    repositories {
        mavenCentral()
    }

```
dependencies {
    classpath 'org.gradle.api.plugins:gradle-cargo-plugin:0.5.9'
}
}

cargo {
containerId = 'tomcat6x'
port = 8084

deployable {
    file = file('build/libs/app.war')
    context = 'app'
}

local {
    homeDir = file('C:/dev/bin/Apache Software Foundation/Apache Tomcat 6.0.35')
    output = file('build/output.log')
    tomcat {
        webappsDir = file('build/libs')
        copyWars = 'true'
        ajpPort = 9091
    }
}
}
```

and here is the relevant end of the exception thrown when I run `gradle cargoStartLocal`

``` Java
Caused by: org.codehaus.cargo.container.ContainerException: Failed to create a Tomcat 6.x container configuration
     at org.codehaus.cargo.container.tomcat.internal.AbstractCatalinaStandaloneLocalConfiguration.setupWebApps(AbstractCatalinaStandaloneLocalConfiguration.j
ava:243)
     at org.codehaus.cargo.container.tomcat.internal.AbstractCatalinaStandaloneLocalConfiguration.doConfigure(AbstractCatalinaStandaloneLocalConfiguration.ja
va:154)
        at org.codehaus.cargo.container.spi.configuration.AbstractLocalConfiguration.configure(AbstractLocalConfiguration.java:210)
        ... 80 more
Caused by: org.codehaus.cargo.util.CargoException: Failed to create folders for path [C:\Users\tomas\AppData\Local\Temp\cargo\conf\C:\dev\data\personal\myproject\build\libs]
        at org.codehaus.cargo.util.DefaultFileHandler.mkdirs(DefaultFileHandler.java:670)
        at org.codehaus.cargo.util.DefaultFileHandler.createDirectory(DefaultFileHandler.java:297)
        at org.codehaus.cargo.container.tomcat.internal.AbstractCatalinaStandaloneLocalConfiguration.setupWebApps(AbstractCatalinaStandaloneLocalConfiguration.j
ava:226)
        ... 82 more
```

It looks like DefaultFileHandler is trying to build wrong path `C:\Users\tomas\AppData\Local\Temp\cargo\conf\C:\dev\data\personal\myproject\build\libs`. I bet I have missed some configuration and it is silly mistake but I can't see it.

Any help would by much appreciated.

Thanks
Tomas

**Comment by sherif181** [comment]
I had this issue too ie:
                                         configFile{
				file=file ( "dao/src/main/resources/ase-ds.xml")
				    toDir = file ("deployments")
			}
this fixed it :
                                      configFile{
				file=new File ( "dao/src/main/resources/ase-ds.xml")
				    toDir = new File ("deployments")
			}

**Comment by bryanmanalo** [comment]
This was also a problem for me.  I am using windows, 64 bit.  I was able to resolve this problem by replacing my tomcat with a zip version instead of using the windows installer.  I think this plugin is running startup.bat which is absent if you used the windows installer.
